### ISSUE TITLE
Processing an image adds 1 pixel black border at the botom

### ISSUE THREAD

**Issue by alexanderabramov** [JimBobSquarePants/ImageProcessor#142]
Hello,

I'm experiencing an issue with the Image Cropper in Umbraco (7.2.2) and one specific image, and its maintainer asked to raise the issue here as internally ImageProcessor library is used.

When I try to crop and resize a specific 600x1100 jpeg image (attached) to 440x880, the resulting image (also attached) gets a 1 pixel black border at the bottom, that is not present in the original image.

These are the URL parameters produced by the image cropper:
.../dress.jpg?crop=0.22275197375166617,0.13995693632728393,0.14282784784168967,0.16794832359274062&cropmode=percentage&width=440&height=880

![dress](https://cloud.githubusercontent.com/assets/96938/6822482/7a261c54-d2e0-11e4-89a4-7e1355c12f60.jpg)
![dress-resized](https://cloud.githubusercontent.com/assets/96938/6822484/7c02829c-d2e0-11e4-8094-4b3575c8b186.jpeg)

**Comment by JimBobSquarePants** [comment]
Hi there,

I think part of the problem relates to #144 which I have fixed with dev. I don't think your output image is getting resized properly.

I see that you are passing both dimensions. Does the aspect ratio of the crop ratio match the aspect ratio of the dimensions for width/height? If not, that would be why you are getting the black line.

Since jpegs have no alpha channel the default correct background output is black. To change this you can either use `bgcolor=fff` to change the background or pass only one resize dimension which will automatically retain the correct aspect ratio of your output image.

I'll have a play around with your image to be sure...

**Comment by JimBobSquarePants** [comment]
Fixed in [v4.3.0](https://www.nuget.org/packages/ImageProcessor.Web/)

**Comment by Pipozor** [comment]
I got same problem in 2.3.1.
In 2.3.0 I used the code below which seems to fix the problem.

                            var image = imageFactory.Load(inStream);
                            image.BackgroundColor(Color.White); 

But the black line is back for some resized images in 2.3.1.

Any advise? thanks

**Comment by JimBobSquarePants** [comment]
Can you show me some code?

**Comment by Pipozor** [comment]
public static bool ImageCropAndResize(string imageSrc, string imageDst, double zoom, double offsetX, double offsetY, float width, float height)
        {
            byte[] photoBytes = File.ReadAllBytes(imageSrc);
            int quality = 90;
            var format = new JpegFormat();

            if (zoom > 1.0)
                zoom = 1.0;

            using (var inStream = new MemoryStream(photoBytes))
            {
                using (var outStream = new MemoryStream())
                {
                    // Initialize the ImageFactory using the overload to preserve EXIF metadata.
                    using (var imageFactory = new ImageFactory(preserveExifData: true))
                    {
                        try
                        {
                            var image = imageFactory.Load(inStream);
                            image.BackgroundColor(Color.White);     // Default Background Color
                            var newW = (int)(image.Image.Width*zoom);
                            var newH = (int)(image.Image.Height*zoom);
                            var cl = new CropLayer((float)Math.Abs(offsetX), (float)Math.Abs(offsetY), width, height, CropMode.Pixels);
                            image.Resize(new Size(newW, newH));
							image.BackgroundColor(Color.White);     // Default Background Color !
							
                            image.Crop(cl);
							image.BackgroundColor(Color.White);     // Default Background Color !!
							
                            image.Format(format)
                                .Quality(quality)
                                .Save(outStream);
                        }
                        catch (Exception ex)
                        {
                            FL.Error("PzImageHelper => ImageCrop => "+ex.Message);
                            return false;
                        }

                        // Save to target file
                        using (FileStream file = new FileStream(imageDst, FileMode.Create, FileAccess.Write))
                        {
                            byte[] bytes = new byte[outStream.Length];
                            outStream.Read(bytes, 0, (int)outStream.Length);
                            file.Write(bytes, 0, bytes.Length);
                            outStream.Close();
                        }
                    }
                }
            }

            return true;
        }


Source image : 
![8ef3ebf4-1d50-4b5f-b37e-d0ee4703066f-0-original](https://cloud.githubusercontent.com/assets/15925712/11956478/b97ca6b0-a8ba-11e5-8366-a4a464581307.jpg)

Thumb image :
![8ef3ebf4-1d50-4b5f-b37e-d0ee4703066f-0](https://cloud.githubusercontent.com/assets/15925712/11956481/bf05cb0c-a8ba-11e5-8f03-191b14eb49a6.jpg)

**Comment by mavenius** [comment]
If you use a zoom of less than .5, does the black line still appear?
Without looking too deeply at it, it feels like it might be related to
rounding.

Thank you,

Mark Avenius

**Comment by JimBobSquarePants** [comment]
Thanks now can you tell me what parameter values you are passing to your method? 

My guess here is the same as @mavenius. That you have a rounding error.

**Comment by Pipozor** [comment]
I can not give you the exact value at the moment but I will do a.s.a.p. .../...

By the way, in case there is a rounding issue that "extends" the image. Would it be possible to use the .BackgroundColor set "to fill/paint" the extra pixels ? or do you think it's too much a "hack".

Or do you mean I need to fix the rounding problem in my code ?

**Comment by Pipozor** [comment]
Zoom = 0.42953020134228187
offsetX = 0
offsetY = 0

but if I'm using image.BackgroundColor(Color.White); 3 times (like in the code) it is well white now.
not very clean but it seems to work

**Comment by JimBobSquarePants** [comment]
Background color will certainly recolor the background but will only work if you're guaranteed to know the background is originally white. You shouldn't need to do it 3 times, do it once, just before you save. You're overwriting it the other times. 


By rounding error I mean, you are probably falling foul of the default rounding down that happens when you cast to an int from a float. 

I'll need the last two float parameters width and height that you are cropping to also please in order to replicate.

**Comment by Pipozor** [comment]
thank you for the reply and suggestions. :)

width= 256
height=256

**Comment by JimBobSquarePants** [comment]
Thanks.. I'll have a go at replicating what is going wrong for you and feedback asap.
