### ISSUE TITLE
The remote host closed the connection

### ISSUE THREAD

**Issue by mortenbock** [JimBobSquarePants/ImageProcessor#625]
Using the following packages

    <package id="ImageProcessor" version="2.5.4" targetFramework="net451" />
    <package id="ImageProcessor.Web" version="4.8.5" targetFramework="net451" />
    <package id="ImageProcessor.Web.Config" version="2.3.0.0" targetFramework="net451" />

In an umbraco 6.2.6 install.

I seem to be getting a lot of this exception in my elmah logs:

`System.Web.HttpException (0x800704CD): The remote host closed the connection. The error code is 0x800704CD.
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpResponse.Flush()
   at System.Web.HttpResponse.End()
   at ImageProcessor.Web.Caching.DiskCache.RewritePath(HttpContext context)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)`

From what I can read, it's not errors that the client sees, since it usually means that the client cancelled the request, and closed the connection: https://stackoverflow.com/questions/8286037/the-remote-host-closed-the-connection-error-how-fix

The question is if ImageProcessor can/should handle it gracefully?

The images are local, so there is no remote.axd stuff going on.

**Comment by JimBobSquarePants** [comment]
Interesting. I wonder if it happens during this method call.

https://github.com/JimBobSquarePants/ImageProcessor/blob/7ddc33f028e974481203a57800a2f882b4433468/src/ImageProcessor.Web/Caching/DiskCache.cs#L325

Would it be possible to wrap that in a try catch locally and give it a try?

**Comment by mortenbock** [comment]
I think the stacktrace looks like it's this line:

https://github.com/JimBobSquarePants/ImageProcessor/blob/7ddc33f028e974481203a57800a2f882b4433468/src/ImageProcessor.Web/Caching/DiskCache.cs#L336

Maybe it makes sense that it throws, since it cannot explicitly flush the response to a closed connection.

Not sure what the best option is. Also not sure how to replicate a closed request connection on a local dev environment :) For now I'm just ignoring the error in my elmah config.

I might try and dig into what happens inside the HttpResponse class, and see if there is a way to make it not throw.

**Comment by mortenbock** [comment]
As a sidenote, I just upgraded from versin 3.x, which did not throw this particular exception, so might also take a look back at what that version did.

**Comment by JimBobSquarePants** [comment]
ImageProcessor.Web 3.x you mean? 

It didn't support caching outside the web root so never ran that code. Caching within the web root lets the StaticFileHandler deal with it.

**Comment by mortenbock** [comment]
Ah, that would explain it. I will dig into the StaticFileHandler as well, to see if there is anything in there that might give a clue how to handle this.

**Comment by mortenbock** [comment]
Looks like the StaticFileHandler do not close the response itself:

https://referencesource.microsoft.com/#System.Web/StaticFileHandler.cs,547

So maybe the code executing handlers does that, and handles any errors. Will dig deeper.

**Comment by JimBobSquarePants** [comment]
Good find. We should copy what StaticFileHander actually does since we can't invoke it.

**Comment by RUGBIN13** [comment]
hi guys,
I'm dealing with  the same problem.. i get an Internal Server Error(500) when i try to use the image processor nuget(i use ImageProcessor 2.5.4, ImageProcessor.Web 4.8.5 and ImageProcessor.Web.Config 2.3.0 )..in my network its look like this
![image](https://user-images.githubusercontent.com/31824473/30250404-4bda1c06-9656-11e7-8b7d-8fd01167de8a.png)
this is the image src = http://myPage.co.il/remote.axd?http://myPageImageStore.co.il/images/Hydrangeas.jpg?anchor=center&mode=crop&width=300&height=319&rnd=131477123780000000
i really do not know what to do with this issue!
any suggestion? tnx reuven

**Comment by mortenbock** [comment]
@RUGBIN13 I think you are seeing a different issue, since the url you have is using the `remote.axd`.

It suggests that your website process is not able to fetch the `myPageImageStore.co.il` domain/url correctly.

**Comment by JimBobSquarePants** [comment]
@RUGBIN13 Tbh I don't recommend using the `RemoteImageService` as anything other than a last resort for domains you don't control. If you control both domains, create a custom service to communicate between the two.

**Comment by shearer3000** [comment]
hi - which release will this fix be in? thanks

**Comment by JimBobSquarePants** [comment]
@shearer3000 This fix was release last year, I can't remember the version number of the top of my head. You should update to the latest release if you can.

**Comment by shearer3000** [comment]
ok great - it says the commit was from 21 days ago so thought i would check. Will try latest now. thanks

**Comment by JimBobSquarePants** [comment]
Nah, it was referenced by a commit to someone else's fork 21 days ago. 

I closed this through https://github.com/JimBobSquarePants/ImageProcessor/commit/657a29eef506796915cfaf9f193050160c318577 on Sep 12, 2017

**Comment by shearer3000** [comment]
thanks :)

**Comment by shearer3000** [comment]
hi - we upgraded to Image Processor 2.6 but our raygun application is still capturing the following YSOD

`System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect):112
System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush():21
System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async):77
System.Web.HttpResponse.Flush():24
System.Web.HttpResponse.End():76
ImageProcessor.Web.Caching.DiskCache.RewritePath(HttpContext context):264
ImageProcessor.Web.HttpModules.ImageProcessingModule+<ProcessImageAsync>d__34.MoveNext():2436`

**Comment by JimBobSquarePants** [comment]
>hi - we upgraded to Image Processor 2.6

Um... You mean you upgraded to ImageProcessor.Web 4.9.1.2? That's where the code is contained.

**Comment by shearer3000** [comment]
oh, no sorry our upgrade left us at:
  <package id="ImageProcessor" version="2.6.0" targetFramework="net462" />
  <package id="ImageProcessor.Web" version="4.8.7" targetFramework="net45" />
  <package id="ImageProcessor.Web.Config" version="2.3.1" targetFramework="net45" />

Will try 4.9.1.2 now. many thanks!

**Comment by ptrocks** [comment]
The current version, its this one ?

https://github.com/JimBobSquarePants/ImageProcessor/tree/new-build

Also getting this error on production, using version 4.8.7 on context.Response.End(); of DiskCache.cs

I think that when this happens the image does not load, but with a ctrl-f5 it does ..

**Comment by ptrocks** [comment]
I'm using cache outside the webroot btw

**Comment by JimBobSquarePants** [comment]
Version 4.9.1.2 on https://www.nuget.org/packages/ImageProcessor.Web/

Does nobody know how to use Nuget anymore? This conversation on a closed issue is beginning to get incredibly frustrating.

**Comment by shearer3000** [comment]
maybe it wouldn't be incredibly frustrating is we could easily tell which version it was fixed in?

**Comment by ptrocks** [comment]
Sorry James, i meant to ask the path to the latest version source code

**Comment by JimBobSquarePants** [comment]
@shearer3000 Since I only support the latest version it doesn't matter.

@ptrocks Source in the default branch `develop` branch is the latest https://github.com/JimBobSquarePants/ImageProcessor/tree/develop

**Comment by avidalzamora** [comment]
Me encontre con el mismo error de ustedes, el problema me daba debido a que tenia una coma en el nombre del archivo.

**Comment by ptrocks** [comment]
Could it be that ? invalid chars ? still getting this error.

52988/15_20180306.jpg?quality=70

for example ^^

Maybe it does not like the underscore in the filename ?

**Comment by sniffdk** [comment]
Hi James
Sorry to bring this up again, but we're experiencing errors like those Morten described a few years ago.

Version numbers:
<package id="ImageProcessor" version="2.7.0.100" targetFramework="net461" />
<package id="ImageProcessor.Web" version="4.10.0.100" targetFramework="net461" />
<package id="ImageProcessor.Web.Config" version="2.5.0.100" targetFramework="net461" />
Umbraco is version 7.12.4, it's running on an Azure web app, and we are also running the cache outside the webroot.
It seems to be all requests made to normal media like eg. "/media/131655/gettyimages-1060693186.jpg"

I've attached the stacktrace if its in anyway relevant.
Not sure if it's an actual problem, but wanted to report it nonetheless.

[data.zip](https://github.com/JimBobSquarePants/ImageProcessor/files/3676983/data.zip)

**Comment by oliverEvry** [comment]
Hi @JimBobSquarePants !

I'm also experiencing these errors. Just like @sniffdk says it seems to be all requests made to normal media.

Running Umbraco 7.15.3 on Azure web app with storageblob for media files and cache outside of webroot.

With the same Image Processor version numbers as @sniffdk

**Comment by JimBobSquarePants** [comment]
Odd... Requests without commands should not be hitting the cache unless you've specifically enabled that behavior.

I'm assuming you're just seeing messages in the logs?

**Comment by sniffdk** [comment]
Yeah, just messages in the log :)
